name: my_project_name
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0' # قم بتحديث هذا الرقم ليتناسب مع الإصدار الذي تستخدمه


# Add regular dependencies here.
dependencies:
  teledart: ^0.6.1

  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
